language: scala
scala:
- 2.11.6
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: L8nnx20YudEmXvUx7UQJIbeNuXRrXrt7AR03dBYyaez2ikGsylLspjYQCnxdAix3X0H0MdBF5miNLo3gwSiRI3ULn55uc90L/cDpTgWCBaW+GB1N2vvYExTZkRNJ+zObmkXuhZ2OpeHjaBuT9cRQAA+1t1QNG8WWQ4VoRjjrA5+tggq8xLjPtouDGwPwBZwnL/9gh66t8r20b06HfCKTEb30lJgGp79Z6ztRfHQSopvLw/gy7DvsaYz1BcuKjPf/0z6S72gHjZ9nn6RLfNY4IS+1rOsjqQMh94X6JHf4AW4Ow5yXBEuWYWFYCbxIY0nSRSAsAeobcV6r6iYzR8wYCz4noHFJL0iThn3w+o2zKO5hy2Qur+NsyscohBE2734Pt91FORMw6x+iiuiBjIGO3idXlLc4gc8Q6pJW8P8OAZwKIq/SIhnQMTc9V29+ToRmXAitJ0tkjXLFvs+b8Jo0DcNVYxJspW/J3ek3Z0qnP18FGBvkgEPGMI4UG/7qIOY34psRcIgJJIZ1CIC3sMa1PVCObOjviCsRJOGxdcxuGif5OiDX2I/Us9b3/KPHm48+2Wn1AWwr7Sp7uXIujQpc8sEoDF/5skEMK5JFE/6IUE+vgI9nDGAOrtwc5zEUNOz+0T8THA7xUC6391+OJQvz5suj59cfHFMguhEhANRxnRE=
  app: froom2-stableweb